### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by uglycow** [ztmajor/AutoLink#1]
控制台输出：

```
[ WARN:0@4.523] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('./IMG/background.jpg'): can't open/read file: check file path/integrity
click 单机连连看
click_point =  (425, 530)
click 无尽模式
click_point =  (442, 728)
Round 1 , Part 1 :
Traceback (most recent call last):
  File "D:\github\AutoLink\Main.py", line 69, in <module>
    matrix = imgp.createMatrix(game_area)
  File "D:\github\AutoLink\ImgProcessor.py", line 28, in createMatrix
    mynet = torch.load('alexnet.pth')
  File "C:\Users\mike\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\mike\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\mike\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'alexnet.pth'
```

看起来仓库里少了 background.jpg 和 'alexnet.pth' 这两个文件。
同学可以修复下么，正在用你这个工程作为学习用。

**Comment by uglycow** [comment]
自己训练了下， alexnet.pth 有了，  background还是没有，但是貌似不影响运行。
